# Generated by Django 4.2.23 on 2025-11-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_class_enrollment_feedback_feedbackitem_markingrubric_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="user",
            table_comment="A table for all user entities, including student, teacher, and admins.",
        ),
    ]
