'use client';

import { localized } from '@/locales';

import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import { ArrowRight, BookOpen, Check, CheckCircle2, FileText, GraduationCap, MessageCircle, PenLine, SearchCheck, ShieldCheck, Sparkles } from 'lucide-react';

type Translate = (en: string, zh?: string) => string;

export function LandingPage() {
  const [language, setLanguage] = useState<'en' | 'zh'>('en');
  const [menuOpen, setMenuOpen] = useState(false);
  const t: Translate = (en, zh) => localized(language, en, zh);

  return <div className='min-h-screen bg-[#f7f9f8] text-[#182f30]'>
    <header className='sticky top-0 z-40 border-b border-slate-200/80 bg-[#f7f9f8]/95 backdrop-blur'>
      <nav className='mx-auto flex max-w-[1440px] items-center justify-between gap-4 px-5 py-4 sm:px-9 lg:px-16' aria-label={t('landing.mainNavigation')}>
        <Link href='/' className='flex items-center gap-3 text-xl font-bold tracking-tight'><span className='grid h-9 w-9 place-items-center rounded-xl bg-[#143f3d] text-white'><PenLine size={19} /></span>EssayCoach</Link>
        <div className='hidden items-center gap-8 text-sm font-semibold text-slate-600 md:flex'><a href='#why' className='hover:text-teal-800'>{t('landing.whyEssaycoach')}</a><a href='#workflow' className='hover:text-teal-800'>{t('landing.howItWorks')}</a><a href='#for-teams' className='hover:text-teal-800'>{t('landing.forYourTeam')}</a></div>
        <div className='hidden items-center gap-3 md:flex'><button type='button' onClick={() => setLanguage(language === 'en' ? 'zh' : 'en')} className='rounded-full border border-slate-300 px-3 py-2 text-xs font-bold'>{language === 'en' ? '中文' : 'English'}</button><Link href='/auth/sign-in' className='rounded-full border border-slate-300 px-4 py-2 text-sm font-semibold'>{t('landing.signIn')}</Link><Link href='/auth/sign-up' className='inline-flex items-center gap-2 rounded-full bg-[#143f3d] px-5 py-2.5 text-sm font-semibold text-white'>{t('landing.useYourInvitation')}<ArrowRight size={15} /></Link></div>
        <button type='button' onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label={t('landing.openMenu')} className='rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold md:hidden'>{menuOpen ? t('landing.close') : t('landing.menu')}</button>
      </nav>
      {menuOpen && <div className='grid gap-3 border-t border-slate-200 px-5 py-4 text-sm font-semibold md:hidden'><a href='#why' onClick={() => setMenuOpen(false)}>{t('landing.whyEssaycoach')}</a><a href='#workflow' onClick={() => setMenuOpen(false)}>{t('landing.howItWorks')}</a><a href='#for-teams' onClick={() => setMenuOpen(false)}>{t('landing.forYourTeam')}</a><Link href='/auth/sign-in'>{t('landing.signIn')}</Link><Link href='/auth/sign-up'>{t('landing.useYourInvitation')}</Link><button type='button' onClick={() => setLanguage(language === 'en' ? 'zh' : 'en')} className='text-left text-teal-800'>{language === 'en' ? '中文' : 'English'}</button></div>}
    </header>

    <main>
      <section className='mx-auto grid max-w-[1440px] items-center gap-14 px-5 py-16 sm:px-9 sm:py-24 lg:grid-cols-[0.94fr_1.06fr] lg:gap-20 lg:px-16 lg:py-28'>
        <div><p className='mb-6 inline-flex items-center gap-2 rounded-full border border-teal-800/15 bg-teal-50 px-3 py-1.5 text-xs font-bold uppercase tracking-widest text-teal-900'><span className='h-1.5 w-1.5 rounded-full bg-teal-600' />{t('landing.aBetterWritingLoop')}</p><h1 className='max-w-2xl text-[clamp(3.2rem,5.5vw,5.8rem)] font-semibold leading-[1.04] tracking-[-0.065em]'>{t('landing.betterWritingGrowsInTheMargins')}</h1><p className='mt-8 max-w-xl text-lg leading-8 text-slate-600'>{t('landing.inInvitedClassesStudentsReviseWithFeedbackBesideTheD')}</p><div className='mt-8 flex flex-wrap gap-3'><Link href='/auth/sign-in' className='inline-flex items-center gap-2 rounded-full bg-[#143f3d] px-6 py-3.5 text-sm font-bold text-white shadow-lg shadow-teal-900/10 hover:bg-[#205450]'>{t('landing.enterTheWorkspace')}<ArrowRight size={18} /></Link><Link href='/auth/sign-up' className='inline-flex items-center gap-2 rounded-full border border-slate-300 bg-white px-6 py-3.5 text-sm font-bold text-[#143f3d] hover:border-teal-700'>{t('landing.acceptAnInvitation')}</Link></div><p className='mt-5 text-sm text-slate-500'>{t('landing.accountsAreCreatedByYourSchoolTeamNoPublicStudent')}</p></div>
        <EditorPreview t={t} />
      </section>

      <section className='border-y border-slate-200 bg-[#edf3f0] px-5 py-6 sm:px-9 lg:px-16'><div className='mx-auto flex max-w-[1312px] flex-wrap items-center justify-between gap-6'><span className='text-xs font-bold uppercase tracking-[0.16em] text-teal-900'>{t('landing.fromDraftToDecision')}</span><div className='flex flex-wrap gap-x-8 gap-y-3 text-sm font-semibold text-[#254544]'><span className='flex items-center gap-2'><PenLine size={18} />{t('landing.draftWithPurpose')}</span><span className='flex items-center gap-2'><SearchCheck size={18} />{t('landing.checkClaims')}</span><span className='flex items-center gap-2'><MessageCircle size={18} />{t('landing.discussFeedback')}</span><span className='flex items-center gap-2'><ShieldCheck size={18} />{t('landing.aHumanConfirms')}</span></div></div></section>

      <section id='why' className='mx-auto max-w-[1440px] scroll-mt-24 px-5 py-20 sm:px-9 lg:px-16 lg:py-28'><p className='text-xs font-bold uppercase tracking-[0.2em] text-teal-800'>01 / {t('landing.theLearningLoop')}</p><h2 className='mt-5 max-w-3xl text-4xl font-semibold leading-tight tracking-tight sm:text-5xl'>{t('landing.everyStepGivesTheWriterANextMove')}</h2><div className='mt-12 grid gap-8 md:grid-cols-3'><Feature icon={<BookOpen size={24} />} title={t('landing.startWithTheBrief')} detail={t('landing.theAssignmentAndRubricStayCloseToTheDraftSo')} /><Feature icon={<Sparkles size={24} />} title={t('landing.notesBesideTheSentence')} detail={t('landing.feedbackPointsToAClaimAsksForEvidenceAndOffers')} /><Feature icon={<GraduationCap size={24} />} title={t('landing.aGradeHasAReviewer')} detail={t('landing.aiDraftsAScoreALecturerReviewsItAndThe')} /></div></section>

      <section id='workflow' className='scroll-mt-24 bg-[#183735] px-5 py-20 text-white sm:px-9 lg:px-16 lg:py-28'><div className='mx-auto grid max-w-[1312px] items-start gap-12 lg:grid-cols-[0.8fr_1.2fr]'><div><p className='text-xs font-bold uppercase tracking-[0.2em] text-teal-200'>02 / {t('landing.howItWorks118375')}</p><h2 className='mt-5 text-4xl font-semibold leading-tight tracking-tight sm:text-5xl'>{t('landing.oneWorkspaceForPracticeAndAssessment')}</h2><p className='mt-5 max-w-lg text-base leading-7 text-teal-50/75'>{t('landing.practiceStaysExploratoryFormalResultsFollowAClearRev')}</p><Link href='/auth/sign-in' className='mt-8 inline-flex items-center gap-2 text-sm font-bold text-teal-200'>{t('landing.seeYourWorkspace')}<ArrowRight size={17} /></Link></div><div className='grid gap-3'><Step number='01' icon={<PenLine size={22} />} title={t('landing.writeAndRevisit')} detail={t('landing.saveADraftImportADocumentAndKeepEachRevision')} /><Step number='02' icon={<SearchCheck size={22} />} title={t('landing.questionTheFeedback')} detail={t('landing.practiceReportsIdentifyClaimsAndShowSourceEvidenceOr')} /><Step number='03' icon={<ShieldCheck size={22} />} title={t('landing.publishWithCare')} detail={t('landing.theTeacherEditsTheAiProposalTheCourseLeadConfirms')} /></div></div></section>

      <section id='for-teams' className='mx-auto grid max-w-[1440px] scroll-mt-24 items-center gap-12 px-5 py-20 sm:px-9 lg:grid-cols-2 lg:px-16 lg:py-28'><div className='rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5 sm:p-9'><div className='flex items-center justify-between border-b border-slate-100 pb-5'><div><p className='text-xs font-bold uppercase tracking-wider text-teal-700'>{t('landing.assessmentReview')}</p><h3 className='mt-1 text-xl font-semibold'>{t('landing.argumentAndEvidence')}</h3></div><span className='rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-800'>{t('landing.awaitingConfirmation')}</span></div><div className='mt-6 grid gap-4'><ReviewRow label={t('landing.claimClarity')} score='8 / 10' /><ReviewRow label={t('landing.sourceUse')} score='7 / 10' /><ReviewRow label={t('landing.structure')} score='9 / 10' /></div><div className='mt-6 rounded-xl bg-teal-50 p-4 text-sm leading-6 text-teal-900'><CheckCircle2 className='mb-2' size={20} />{t('landing.lecturerReviewRecordedCourseLeadConfirmationIsStillR')}</div></div><div><p className='text-xs font-bold uppercase tracking-[0.2em] text-teal-800'>03 / {t('landing.builtForTeachingTeams')}</p><h2 className='mt-5 text-4xl font-semibold leading-tight tracking-tight sm:text-5xl'>{t('landing.usefulForStudentsAccountableForTeachers')}</h2><p className='mt-6 text-base leading-8 text-slate-600'>{t('landing.inviteStudentsIntoTheRightClassKeepPracticeSeparateF')}</p><ul className='mt-7 space-y-3 text-sm font-semibold text-slate-700'><li className='flex items-center gap-3'><Check className='text-teal-700' size={18} />{t('landing.invitationOnlyAccess')}</li><li className='flex items-center gap-3'><Check className='text-teal-700' size={18} />{t('landing.courseScopedPermissions')}</li><li className='flex items-center gap-3'><Check className='text-teal-700' size={18} />{t('landing.reviewAndPublicationHistory')}</li></ul></div></section>

      <section className='bg-[#e8f0eb] px-5 py-16 sm:px-9 lg:px-16'><div className='mx-auto flex max-w-[1312px] flex-wrap items-center justify-between gap-8'><div><p className='text-xs font-bold uppercase tracking-[0.2em] text-teal-800'>{t('landing.readyToWrite')}</p><h2 className='mt-3 text-3xl font-semibold tracking-tight'>{t('landing.yourNextDraftStartsHere')}</h2></div><Link href='/auth/sign-in' className='inline-flex items-center gap-2 rounded-full bg-[#143f3d] px-6 py-3.5 text-sm font-bold text-white'>{t('landing.enterEssaycoach')}<ArrowRight size={18} /></Link></div></section>
    </main>

    <footer className='border-t border-slate-200 bg-[#f7f9f8] px-5 py-8 text-sm text-slate-500 sm:px-9 lg:px-16'><div className='mx-auto flex max-w-[1312px] flex-wrap items-center justify-between gap-5'><span className='font-bold text-slate-800'>EssayCoach</span><span>{t('landing.privateLocalWorkspaceForInvitedSchoolCommunities')}</span><div className='flex gap-5'><Link href='/auth/sign-in' className='hover:text-teal-800'>{t('landing.signIn')}</Link><Link href='/auth/sign-up' className='hover:text-teal-800'>{t('landing.invitation')}</Link></div></div></footer>
  </div>;
}

function EditorPreview({ t }: { t: Translate }) {
  return <div className='overflow-hidden rounded-[22px] border border-[#dbe5e0] bg-white shadow-[0_28px_80px_rgba(29,63,58,0.13)]' aria-label={t('landing.exampleAnnotatedEssay')}><div className='flex items-center justify-between border-b border-slate-100 bg-[#f8faf8] px-5 py-4 text-xs font-semibold text-slate-500'><span className='flex items-center gap-2 text-slate-700'><FileText size={16} />{t('landing.draft02')}</span><span>{t('landing.argumentEssay')}</span></div><div className='relative min-h-[390px] bg-[linear-gradient(90deg,#fff_78%,#f3f8f5_78%)] px-6 py-10 sm:px-10 sm:py-12'><div className='max-w-[75%]'><p className='text-[11px] font-bold uppercase tracking-[0.15em] text-teal-700'>{t('landing.learningToThinkWithAi')}</p><h2 className='mt-5 font-serif text-[clamp(1.45rem,2vw,2rem)] leading-tight'>{t('landing.whoOwnsTheFinalJudgment')}</h2><p className='mt-6 font-serif text-sm leading-8 text-slate-600'>{t('landing.aiCanMakeFeedbackFasterButGoodWritingStillDepends')}</p><p className='mt-5 font-serif text-sm leading-8 text-slate-600'><mark className='border-b-2 border-teal-600 bg-teal-100/70 text-inherit'>{t('landing.aScoreAloneRarelyExplainsHowAnArgumentCanImprove')}</mark> {t('landing.writersNeedToSeeTheReasoningBehindEachSuggestion')}</p></div><div className='absolute right-3 top-[53%] w-[18%] text-teal-900 sm:right-5'><span className='grid h-6 w-6 place-items-center rounded-full bg-[#1d6157] text-xs font-bold text-white'>1</span><strong className='mt-3 block text-xs leading-tight'>{t('landing.makeTheClaimSpecific')}</strong><small className='mt-2 block text-[10px] leading-relaxed text-slate-500'>{t('landing.whatEvidenceCouldSupportThis')}</small></div></div><div className='flex items-center justify-between border-t border-slate-100 bg-[#f8faf8] px-5 py-4 text-xs text-slate-500'><span className='flex items-center gap-2'><span className='h-2 w-2 rounded-full bg-teal-500' />{t('landing.feedbackReadyToReview')}</span><span>{t('landing.writingStudio')}</span></div></div>;
}

function Feature({ icon, title, detail }: { icon: ReactNode; title: string; detail: string }) {
  return <article className='border-t border-slate-300 pt-6'><span className='text-teal-700'>{icon}</span><h3 className='mt-5 text-xl font-semibold'>{title}</h3><p className='mt-3 leading-7 text-slate-600'>{detail}</p></article>;
}

function Step({ number, icon, title, detail }: { number: string; icon: ReactNode; title: string; detail: string }) {
  return <div className='grid grid-cols-[2.5rem_1fr] gap-4 rounded-2xl border border-white/15 bg-white/5 p-5 sm:grid-cols-[2.5rem_2.5rem_1fr] sm:items-center'><span className='font-mono text-xs text-teal-200'>{number}</span><span className='text-teal-200'>{icon}</span><div className='col-start-2 sm:col-start-3'><h3 className='font-semibold'>{title}</h3><p className='mt-1 text-sm leading-6 text-teal-50/70'>{detail}</p></div></div>;
}

function ReviewRow({ label, score }: { label: string; score: string }) {
  return <div className='flex items-center justify-between rounded-xl border border-slate-100 bg-[#fbfcfb] px-4 py-3 text-sm'><span>{label}</span><strong className='text-teal-800'>{score}</strong></div>;
}
