'use client';

import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import { ArrowRight, BookOpen, Check, CheckCircle2, FileText, GraduationCap, MessageCircle, PenLine, SearchCheck, ShieldCheck, Sparkles } from 'lucide-react';

type Translate = (en: string, zh: string) => string;

export function LandingPage() {
  const [language, setLanguage] = useState<'en' | 'zh'>('en');
  const [menuOpen, setMenuOpen] = useState(false);
  const t: Translate = (en, zh) => language === 'zh' ? zh : en;

  return <div className='min-h-screen bg-[#f7f9f8] text-[#182f30]'>
    <header className='sticky top-0 z-40 border-b border-slate-200/80 bg-[#f7f9f8]/95 backdrop-blur'>
      <nav className='mx-auto flex max-w-[1440px] items-center justify-between gap-4 px-5 py-4 sm:px-9 lg:px-16' aria-label={t('Main navigation', '主导航')}>
        <Link href='/' className='flex items-center gap-3 text-xl font-bold tracking-tight'><span className='grid h-9 w-9 place-items-center rounded-xl bg-[#143f3d] text-white'><PenLine size={19} /></span>EssayCoach</Link>
        <div className='hidden items-center gap-8 text-sm font-semibold text-slate-600 md:flex'><a href='#why' className='hover:text-teal-800'>{t('Why EssayCoach', '产品理念')}</a><a href='#workflow' className='hover:text-teal-800'>{t('How it works', '使用流程')}</a><a href='#for-teams' className='hover:text-teal-800'>{t('For your team', '团队协作')}</a></div>
        <div className='hidden items-center gap-3 md:flex'><button type='button' onClick={() => setLanguage(language === 'en' ? 'zh' : 'en')} className='rounded-full border border-slate-300 px-3 py-2 text-xs font-bold'>{language === 'en' ? '中文' : 'English'}</button><Link href='/auth/sign-in' className='rounded-full border border-slate-300 px-4 py-2 text-sm font-semibold'>{t('Sign in', '登录')}</Link><Link href='/auth/sign-up' className='inline-flex items-center gap-2 rounded-full bg-[#143f3d] px-5 py-2.5 text-sm font-semibold text-white'>{t('Use your invitation', '使用邀请')}<ArrowRight size={15} /></Link></div>
        <button type='button' onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label={t('Open menu', '打开菜单')} className='rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold md:hidden'>{menuOpen ? t('Close', '关闭') : t('Menu', '菜单')}</button>
      </nav>
      {menuOpen && <div className='grid gap-3 border-t border-slate-200 px-5 py-4 text-sm font-semibold md:hidden'><a href='#why' onClick={() => setMenuOpen(false)}>{t('Why EssayCoach', '产品理念')}</a><a href='#workflow' onClick={() => setMenuOpen(false)}>{t('How it works', '使用流程')}</a><a href='#for-teams' onClick={() => setMenuOpen(false)}>{t('For your team', '团队协作')}</a><Link href='/auth/sign-in'>{t('Sign in', '登录')}</Link><Link href='/auth/sign-up'>{t('Use your invitation', '使用邀请')}</Link><button type='button' onClick={() => setLanguage(language === 'en' ? 'zh' : 'en')} className='text-left text-teal-800'>{language === 'en' ? '中文' : 'English'}</button></div>}
    </header>

    <main>
      <section className='mx-auto grid max-w-[1440px] items-center gap-14 px-5 py-16 sm:px-9 sm:py-24 lg:grid-cols-[0.94fr_1.06fr] lg:gap-20 lg:px-16 lg:py-28'>
        <div><p className='mb-6 inline-flex items-center gap-2 rounded-full border border-teal-800/15 bg-teal-50 px-3 py-1.5 text-xs font-bold uppercase tracking-widest text-teal-900'><span className='h-1.5 w-1.5 rounded-full bg-teal-600' />{t('A better writing loop', '让写作形成更好的循环')}</p><h1 className='max-w-2xl text-[clamp(3.2rem,5.5vw,5.8rem)] font-semibold leading-[1.04] tracking-[-0.065em]'>{t('Better writing grows in the margins.', '好文章，写在每一次修改之间。')}</h1><p className='mt-8 max-w-xl text-lg leading-8 text-slate-600'>{t('In invited classes, students revise with feedback beside the draft. Lecturers refine AI suggestions; course leads confirm every formal grade.', '在受邀班级中，学生对照正文旁的反馈修改草稿。讲师复核 AI 建议，课程负责人确认每一份正式成绩。')}</p><div className='mt-8 flex flex-wrap gap-3'><Link href='/auth/sign-in' className='inline-flex items-center gap-2 rounded-full bg-[#143f3d] px-6 py-3.5 text-sm font-bold text-white shadow-lg shadow-teal-900/10 hover:bg-[#205450]'>{t('Enter the workspace', '进入工作空间')}<ArrowRight size={18} /></Link><Link href='/auth/sign-up' className='inline-flex items-center gap-2 rounded-full border border-slate-300 bg-white px-6 py-3.5 text-sm font-bold text-[#143f3d] hover:border-teal-700'>{t('Accept an invitation', '接受邀请')}</Link></div><p className='mt-5 text-sm text-slate-500'>{t('Accounts are created by your school team. No public student registration.', '账户由学校团队邀请创建，不开放学生自行注册。')}</p></div>
        <EditorPreview t={t} />
      </section>

      <section className='border-y border-slate-200 bg-[#edf3f0] px-5 py-6 sm:px-9 lg:px-16'><div className='mx-auto flex max-w-[1312px] flex-wrap items-center justify-between gap-6'><span className='text-xs font-bold uppercase tracking-[0.16em] text-teal-900'>{t('From draft to decision', '从草稿到最终决定')}</span><div className='flex flex-wrap gap-x-8 gap-y-3 text-sm font-semibold text-[#254544]'><span className='flex items-center gap-2'><PenLine size={18} />{t('Draft with purpose', '有目标地写作')}</span><span className='flex items-center gap-2'><SearchCheck size={18} />{t('Check claims', '核实论断')}</span><span className='flex items-center gap-2'><MessageCircle size={18} />{t('Discuss feedback', '讨论反馈')}</span><span className='flex items-center gap-2'><ShieldCheck size={18} />{t('A human confirms', '由教师确认')}</span></div></div></section>

      <section id='why' className='mx-auto max-w-[1440px] scroll-mt-24 px-5 py-20 sm:px-9 lg:px-16 lg:py-28'><p className='text-xs font-bold uppercase tracking-[0.2em] text-teal-800'>01 / {t('THE LEARNING LOOP', '学习循环')}</p><h2 className='mt-5 max-w-3xl text-4xl font-semibold leading-tight tracking-tight sm:text-5xl'>{t('Every step gives the writer a next move.', '每一步，都让写作者知道下一步怎么做。')}</h2><div className='mt-12 grid gap-8 md:grid-cols-3'><Feature icon={<BookOpen size={24} />} title={t('Start with the brief', '先看清写作要求')} detail={t('The assignment and rubric stay close to the draft, so students know what the course asks of them.', '题目和评分标准就在草稿旁，学生动笔前就知道课程要求。')} /><Feature icon={<Sparkles size={24} />} title={t('Notes beside the sentence', '批注紧贴原句')} detail={t('Feedback points to a claim, asks for evidence, and offers a concrete revision task.', '反馈指向具体论断，提醒学生补充证据，并给出明确的修改任务。')} /><Feature icon={<GraduationCap size={24} />} title={t('A grade has a reviewer', '正式成绩有人复核')} detail={t('AI drafts a score. A lecturer reviews it, and the course lead decides when to publish.', 'AI 起草分数，讲师复核，课程负责人决定何时发布。')} /></div></section>

      <section id='workflow' className='scroll-mt-24 bg-[#183735] px-5 py-20 text-white sm:px-9 lg:px-16 lg:py-28'><div className='mx-auto grid max-w-[1312px] items-start gap-12 lg:grid-cols-[0.8fr_1.2fr]'><div><p className='text-xs font-bold uppercase tracking-[0.2em] text-teal-200'>02 / {t('HOW IT WORKS', '使用流程')}</p><h2 className='mt-5 text-4xl font-semibold leading-tight tracking-tight sm:text-5xl'>{t('One workspace for practice and assessment.', '练习与正式评价，各得其所。')}</h2><p className='mt-5 max-w-lg text-base leading-7 text-teal-50/75'>{t('Practice stays exploratory. Formal results follow a clear review and publication path, with every change recorded.', '练习可以反复探索；正式成绩经过清晰的复核与发布流程，每一步都有记录。')}</p><Link href='/auth/sign-in' className='mt-8 inline-flex items-center gap-2 text-sm font-bold text-teal-200'>{t('See your workspace', '查看工作空间')}<ArrowRight size={17} /></Link></div><div className='grid gap-3'><Step number='01' icon={<PenLine size={22} />} title={t('Write and revisit', '写作与修改')} detail={t('Save a draft, import a document, and keep each revision.', '保存草稿、导入文档，并保留每次修改。')} /><Step number='02' icon={<SearchCheck size={22} />} title={t('Question the feedback', '核查反馈依据')} detail={t('Practice reports identify claims and show source evidence or unresolved checks.', '练习报告标出待核实论断，展示来源证据或明确标记未解决的问题。')} /><Step number='03' icon={<ShieldCheck size={22} />} title={t('Publish with care', '审慎发布成绩')} detail={t('The teacher edits the AI proposal. The course lead confirms before students see a grade.', '教师修改 AI 建议，课程负责人确认后学生才会看到成绩。')} /></div></div></section>

      <section id='for-teams' className='mx-auto grid max-w-[1440px] scroll-mt-24 items-center gap-12 px-5 py-20 sm:px-9 lg:grid-cols-2 lg:px-16 lg:py-28'><div className='rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5 sm:p-9'><div className='flex items-center justify-between border-b border-slate-100 pb-5'><div><p className='text-xs font-bold uppercase tracking-wider text-teal-700'>{t('Assessment review', '成绩复核')}</p><h3 className='mt-1 text-xl font-semibold'>{t('Argument and evidence', '论点与证据')}</h3></div><span className='rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-800'>{t('Awaiting confirmation', '等待确认')}</span></div><div className='mt-6 grid gap-4'><ReviewRow label={t('Claim clarity', '论点清晰度')} score='8 / 10' /><ReviewRow label={t('Source use', '来源使用')} score='7 / 10' /><ReviewRow label={t('Structure', '文章结构')} score='9 / 10' /></div><div className='mt-6 rounded-xl bg-teal-50 p-4 text-sm leading-6 text-teal-900'><CheckCircle2 className='mb-2' size={20} />{t('Lecturer review recorded. Course lead confirmation is still required.', '讲师复核已记录，仍需课程负责人确认。')}</div></div><div><p className='text-xs font-bold uppercase tracking-[0.2em] text-teal-800'>03 / {t('BUILT FOR TEACHING TEAMS', '为教学团队设计')}</p><h2 className='mt-5 text-4xl font-semibold leading-tight tracking-tight sm:text-5xl'>{t('Useful for students. Accountable for teachers.', '让学生看见进步，让教师掌握决定。')}</h2><p className='mt-6 text-base leading-8 text-slate-600'>{t('Invite students into the right class, keep practice separate from formal marks, and look at released progress across a class or course.', '邀请学生进入正确班级，区分练习与正式成绩，并查看班级和课程的已发布进展。')}</p><ul className='mt-7 space-y-3 text-sm font-semibold text-slate-700'><li className='flex items-center gap-3'><Check className='text-teal-700' size={18} />{t('Invitation-only access', '仅限邀请加入')}</li><li className='flex items-center gap-3'><Check className='text-teal-700' size={18} />{t('Course-scoped permissions', '按课程限定权限')}</li><li className='flex items-center gap-3'><Check className='text-teal-700' size={18} />{t('Review and publication history', '完整的复核与发布记录')}</li></ul></div></section>

      <section className='bg-[#e8f0eb] px-5 py-16 sm:px-9 lg:px-16'><div className='mx-auto flex max-w-[1312px] flex-wrap items-center justify-between gap-8'><div><p className='text-xs font-bold uppercase tracking-[0.2em] text-teal-800'>{t('READY TO WRITE?', '准备开始写作？')}</p><h2 className='mt-3 text-3xl font-semibold tracking-tight'>{t('Your next draft starts here.', '从下一稿开始，写得更好。')}</h2></div><Link href='/auth/sign-in' className='inline-flex items-center gap-2 rounded-full bg-[#143f3d] px-6 py-3.5 text-sm font-bold text-white'>{t('Enter EssayCoach', '进入 EssayCoach')}<ArrowRight size={18} /></Link></div></section>
    </main>

    <footer className='border-t border-slate-200 bg-[#f7f9f8] px-5 py-8 text-sm text-slate-500 sm:px-9 lg:px-16'><div className='mx-auto flex max-w-[1312px] flex-wrap items-center justify-between gap-5'><span className='font-bold text-slate-800'>EssayCoach</span><span>{t('Private local workspace for invited school communities.', '面向受邀学校群体的私有本地工作空间。')}</span><div className='flex gap-5'><Link href='/auth/sign-in' className='hover:text-teal-800'>{t('Sign in', '登录')}</Link><Link href='/auth/sign-up' className='hover:text-teal-800'>{t('Invitation', '邀请')}</Link></div></div></footer>
  </div>;
}

function EditorPreview({ t }: { t: Translate }) {
  return <div className='overflow-hidden rounded-[22px] border border-[#dbe5e0] bg-white shadow-[0_28px_80px_rgba(29,63,58,0.13)]' aria-label={t('Example annotated essay', '作文批注示例')}><div className='flex items-center justify-between border-b border-slate-100 bg-[#f8faf8] px-5 py-4 text-xs font-semibold text-slate-500'><span className='flex items-center gap-2 text-slate-700'><FileText size={16} />{t('Draft 02', '草稿 02')}</span><span>{t('Argument essay', '议论文')}</span></div><div className='relative min-h-[390px] bg-[linear-gradient(90deg,#fff_78%,#f3f8f5_78%)] px-6 py-10 sm:px-10 sm:py-12'><div className='max-w-[75%]'><p className='text-[11px] font-bold uppercase tracking-[0.15em] text-teal-700'>{t('Learning to think with AI', '与 AI 一起学习思考')}</p><h2 className='mt-5 font-serif text-[clamp(1.45rem,2vw,2rem)] leading-tight'>{t('Who owns the final judgment?', '谁来作出最终判断？')}</h2><p className='mt-6 font-serif text-sm leading-8 text-slate-600'>{t('AI can make feedback faster, but good writing still depends on a conversation between a student and a teacher.', 'AI 可以让反馈更及时，但好的写作仍离不开学生与教师之间的对话。')}</p><p className='mt-5 font-serif text-sm leading-8 text-slate-600'><mark className='border-b-2 border-teal-600 bg-teal-100/70 text-inherit'>{t('A score alone rarely explains how an argument can improve.', '仅有分数，很难说明论证该如何进步。')}</mark> {t('Writers need to see the reasoning behind each suggestion.', '写作者需要理解每一条建议背后的理由。')}</p></div><div className='absolute right-3 top-[53%] w-[18%] text-teal-900 sm:right-5'><span className='grid h-6 w-6 place-items-center rounded-full bg-[#1d6157] text-xs font-bold text-white'>1</span><strong className='mt-3 block text-xs leading-tight'>{t('Make the claim specific', '让论点更具体')}</strong><small className='mt-2 block text-[10px] leading-relaxed text-slate-500'>{t('What evidence could support this?', '可以用什么证据支持？')}</small></div></div><div className='flex items-center justify-between border-t border-slate-100 bg-[#f8faf8] px-5 py-4 text-xs text-slate-500'><span className='flex items-center gap-2'><span className='h-2 w-2 rounded-full bg-teal-500' />{t('Feedback ready to review', '反馈可供查看')}</span><span>{t('Writing studio', '写作空间')}</span></div></div>;
}

function Feature({ icon, title, detail }: { icon: ReactNode; title: string; detail: string }) {
  return <article className='border-t border-slate-300 pt-6'><span className='text-teal-700'>{icon}</span><h3 className='mt-5 text-xl font-semibold'>{title}</h3><p className='mt-3 leading-7 text-slate-600'>{detail}</p></article>;
}

function Step({ number, icon, title, detail }: { number: string; icon: ReactNode; title: string; detail: string }) {
  return <div className='grid grid-cols-[2.5rem_1fr] gap-4 rounded-2xl border border-white/15 bg-white/5 p-5 sm:grid-cols-[2.5rem_2.5rem_1fr] sm:items-center'><span className='font-mono text-xs text-teal-200'>{number}</span><span className='text-teal-200'>{icon}</span><div className='col-start-2 sm:col-start-3'><h3 className='font-semibold'>{title}</h3><p className='mt-1 text-sm leading-6 text-teal-50/70'>{detail}</p></div></div>;
}

function ReviewRow({ label, score }: { label: string; score: string }) {
  return <div className='flex items-center justify-between rounded-xl border border-slate-100 bg-[#fbfcfb] px-4 py-3 text-sm'><span>{label}</span><strong className='text-teal-800'>{score}</strong></div>;
}
