"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For a full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import secrets
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment variable or generate a safe default for development
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or secrets.token_urlsafe(50)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG should be explicitly set via environment variable for production safety
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

# Helper for conditional settings (e.g., debug-only features)
IS_DEBUGGING = DEBUG

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",  # For token-based authentication
    "django_filters",
    "drf_spectacular",  # OpenAPI 3.0 schema generation
    "django_extensions",  # Management commands including graph_models for ERD
    # Custom Apps
    "core",
    "auth",
    "analytics",
    "ai_feedback",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "essay_coach.middleware.PostSlashRedirectMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5100",
    "http://localhost:3000",
    "http://127.0.0.1:5100",
    "http://127.0.0.1:3000",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5100",
    "http://localhost:3000",
    "http://127.0.0.1:5100",
    "http://127.0.0.1:3000",
]

# Django REST Framework settings (DRF global)
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ]
    + (["rest_framework.authentication.BasicAuthentication"] if IS_DEBUGGING else []),
}

# drf-spectacular settings for OpenAPI 3.0 documentation
SPECTACULAR_SETTINGS = {
    "TITLE": "EssayCoach API",
    "DESCRIPTION": (
        "Comprehensive REST API documentation for EssayCoach - An intelligent "
        "essay feedback platform that leverages AI to provide students with "
        "instant, in-depth, multi-dimensional essay feedback."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/v1",
    "AUTHENTICATION_WHITELIST": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ]
    + (["rest_framework.authentication.BasicAuthentication"] if IS_DEBUGGING else []),
    "TAGS": [
        {
            "name": "Authentication",
            "description": "User authentication and authorization endpoints",
        },
        {"name": "Users", "description": "User management endpoints"},
        {
            "name": "Courses",
            "description": ("Course structure management (Units, Classes, Enrollments, Teaching Assignments)"),
        },
        {
            "name": "Rubrics",
            "description": (
                "Rubric configuration and management (Marking Rubrics, Rubric Items, Rubric Level Descriptions)"
            ),
        },
        {"name": "Tasks", "description": "Assignment and task management"},
        {"name": "Submissions", "description": "Student submission management"},
        {
            "name": "Feedback",
            "description": "Feedback and evaluation management (Feedbacks, Feedback Items)",
        },
    ],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "displayOperationId": True,
        "filter": True,
        "showExtensions": True,
        "showCommonExtensions": True,
    },
    "REDOC": {
        "hideHostname": False,
        "showApiVersion": True,
    },
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
    ],
    "ENUM_NAME_OVERRIDES": {
        # Override enum names for better documentation
    },
}

ROOT_URLCONF = "essay_coach.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "essay_coach.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

IS_TESTING = "pytest" in sys.modules or "test" in sys.argv

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "essaycoach"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
        # IMPORTANT: Use explicit IPv4 address (127.0.0.1) to avoid IPv6/IPv4
        # resolution issues with Node.js v24+ and Python's psycopg2 on macOS
        "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# Environment-aware Dify defaults
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Use custom user model
AUTH_USER_MODEL = "core.User"

# SiliconFlow AI Configuration (for rubric parsing)
SILICONFLOW_API_KEY = os.environ.get("SILICONFLOW_API_KEY", "")
SILICONFLOW_API_URL = "https://api.siliconflow.cn/v1/chat/completions"  # 使用正确的.cn域名
SILICONFLOW_MODEL = "Qwen/Qwen3-Next-80B-A3B-Instruct"

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[%(levelname)s] [%(asctime)s] %(name)s\n%(message)s",
            "datefmt": "%d/%b/%Y %H:%M:%S",
        },
        "simple": {
            "format": "[%(levelname)s] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "verbose",
            "filename": str(BASE_DIR / "logs" / "essaycoach.log"),
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 5,
            "encoding": "utf-8",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "core": {
            "handlers": ["console", "file"],
            "level": "DEBUG",  # More verbose for app-specific logs
            "propagate": False,
        },
        "ai_feedback": {
            "handlers": ["console", "file"],
            "level": "DEBUG",  # More verbose for AI-related logs
            "propagate": False,
        },
    },
}
