# Generated by Django 4.2.23 on 2025-11-30 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_id",
                    models.AutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        db_column="user_email", max_length=254, unique=True
                    ),
                ),
                (
                    "user_fname",
                    models.CharField(
                        blank=True, db_column="user_fname", max_length=20, null=True
                    ),
                ),
                (
                    "user_lname",
                    models.CharField(
                        blank=True, db_column="user_lname", max_length=20, null=True
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        blank=True, db_column="user_role", max_length=10, null=True
                    ),
                ),
                (
                    "user_status",
                    models.CharField(
                        blank=True, db_column="user_status", max_length=15, null=True
                    ),
                ),
                (
                    "password",
                    models.CharField(db_column="user_credential", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "user",
                "db_table_comment": "A table for all user entities, including student, teacher, and admins.",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "class_id",
                    models.SmallAutoField(
                        db_comment="Unique identifier for a class under a unit",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "class_size",
                    models.SmallIntegerField(
                        db_comment="current number of students in the class", default=0
                    ),
                ),
            ],
            options={
                "verbose_name": "class",
                "verbose_name_plural": "classes",
                "db_table": "class",
                "db_table_comment": "A table for class entity",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "feedback",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MarkingRubric",
            fields=[
                (
                    "rubric_id",
                    models.AutoField(
                        db_comment="unique identifier for rubrics",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rubric_create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="timestamp when the rubirc is created",
                    ),
                ),
                (
                    "rubric_desc",
                    models.CharField(
                        blank=True,
                        db_comment="description to the rubrics",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user_id_user",
                    models.ForeignKey(
                        db_column="user_id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marking_rubric",
                "db_table_comment": "entity for a marking rubric. A marking rubric has many items.",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RubricItem",
            fields=[
                (
                    "rubric_item_id",
                    models.AutoField(
                        db_comment="unique identifier for item",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rubric_item_name",
                    models.CharField(
                        db_comment="Title(header) name for the item", max_length=50
                    ),
                ),
                (
                    "rubric_item_weight",
                    models.DecimalField(
                        db_comment="the weight of the item on a scale of 100%, using xx.x",
                        decimal_places=1,
                        max_digits=3,
                    ),
                ),
                (
                    "rubric_id_marking_rubric",
                    models.ForeignKey(
                        db_column="rubric_id_marking_rubric",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.markingrubric",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_item",
                "db_table_comment": "An item(dimension) under one rubric",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "unit_id",
                    models.CharField(
                        db_comment="Unique identifier for each unit, same as the unit code",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(db_comment="Full name of the unit", max_length=50),
                ),
                (
                    "unit_desc",
                    models.TextField(
                        blank=True, db_comment="details of the unit", null=True
                    ),
                ),
            ],
            options={
                "db_table": "unit",
                "db_table_comment": "A table for unit entity",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TeachingAssn",
            fields=[
                (
                    "teaching_assn_id",
                    models.SmallAutoField(
                        db_comment="unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "class_id_class",
                    models.ForeignKey(
                        db_column="class_id_class",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.class",
                    ),
                ),
                (
                    "user_id_user",
                    models.ForeignKey(
                        db_column="user_id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teaching_assn",
                "db_table_comment": "A weak entity for assignment of teacher to classes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_id",
                    models.AutoField(
                        db_comment="Unique identifier for task.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_publish_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="time/date when the task is published",
                    ),
                ),
                (
                    "task_due_datetime",
                    models.DateTimeField(db_comment="time/date when the task is due"),
                ),
                (
                    "rubric_id_marking_rubric",
                    models.ForeignKey(
                        db_column="rubric_id_marking_rubric",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.markingrubric",
                    ),
                ),
                (
                    "unit_id_unit",
                    models.ForeignKey(
                        db_column="unit_id_unit",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.unit",
                    ),
                ),
            ],
            options={
                "db_table": "task",
                "db_table_comment": "Task created by lecturer/admin for students in some classes/units to complete",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "submission_id",
                    models.AutoField(
                        db_comment="unique identifier for submission",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submission_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="time/date of submission"
                    ),
                ),
                (
                    "submission_txt",
                    models.TextField(
                        db_comment="complete content of the essay submission"
                    ),
                ),
                (
                    "task_id_task",
                    models.ForeignKey(
                        db_column="task_id_task",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.task",
                    ),
                ),
                (
                    "user_id_user",
                    models.ForeignKey(
                        db_column="user_id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submission",
                "db_table_comment": "A weal entity for task submissions.",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RubricLevelDesc",
            fields=[
                (
                    "level_desc_id",
                    models.AutoField(
                        db_comment="unique identifier for each level desc under one rubric",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level_min_score",
                    models.SmallIntegerField(db_comment="min for the item"),
                ),
                (
                    "level_max_score",
                    models.SmallIntegerField(db_comment="max for the item"),
                ),
                ("level_desc", models.TextField()),
                (
                    "rubric_item_id_rubric_item",
                    models.ForeignKey(
                        db_column="rubric_item_id_rubric_item",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.rubricitem",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_level_desc",
                "db_table_comment": "The detailed description to each of the score range under a rubric item under a rubric.",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FeedbackItem",
            fields=[
                (
                    "feedback_item_id",
                    models.AutoField(
                        db_comment="unique identifier for feedback item",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_item_score",
                    models.SmallIntegerField(db_comment="actual score of the item"),
                ),
                (
                    "feedback_item_comment",
                    models.TextField(
                        blank=True,
                        db_comment="short description to the sub-item grade",
                        null=True,
                    ),
                ),
                (
                    "feedback_item_source",
                    models.CharField(
                        db_comment="the source of feedback: \nai, human, or revised if ai feedback is slightly modifed by human",
                        max_length=10,
                    ),
                ),
                (
                    "feedback_id_feedback",
                    models.ForeignKey(
                        db_column="feedback_id_feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.feedback",
                    ),
                ),
                (
                    "rubric_item_id_rubric_item",
                    models.ForeignKey(
                        db_column="rubric_item_id_rubric_item",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.rubricitem",
                    ),
                ),
            ],
            options={
                "db_table": "feedback_item",
                "db_table_comment": "A section in the feedback as per the rubric",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="submission_id_submission",
            field=models.OneToOneField(
                db_column="submission_id_submission",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.submission",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user_id_user",
            field=models.ForeignKey(
                db_column="user_id_user",
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "enrollment_id",
                    models.AutoField(
                        db_comment="Unique identifier for each enrollment",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrollment_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="The time when the student is enrolled in the DBMS",
                    ),
                ),
                (
                    "class_id_class",
                    models.ForeignKey(
                        db_column="class_id_class",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.class",
                    ),
                ),
                (
                    "unit_id_unit",
                    models.ForeignKey(
                        db_column="unit_id_unit",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.unit",
                    ),
                ),
                (
                    "user_id_user",
                    models.ForeignKey(
                        db_column="user_id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "enrollment",
                "db_table_comment": "The enrollment of student to a specific class. A student can only have one enrollment to one class of one unit anytime.",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="class",
            name="unit_id_unit",
            field=models.ForeignKey(
                db_column="unit_id_unit",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingassn",
            constraint=models.UniqueConstraint(
                fields=("user_id_user", "class_id_class"),
                name="lecturer_id_class_id_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("task_publish_datetime__lt", models.F("task_due_datetime"))
                ),
                name="task_publish_time_task_due_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="rubricleveldesc",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("level_min_score__gte", 0),
                    ("level_max_score__gt", 0),
                    ("level_min_score__lt", models.F("level_max_score")),
                ),
                name="min_max_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="rubricitem",
            constraint=models.CheckConstraint(
                check=models.Q(("rubric_item_weight__gt", 0)), name="item_weight_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedbackitem",
            constraint=models.UniqueConstraint(
                fields=("feedback_id_feedback", "rubric_item_id_rubric_item"),
                name="feedback_id_rubric_item_id_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedbackitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("feedback_item_source__in", ["ai", "human", "revised"])
                ),
                name="feedback_item_source_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("user_id_user", "class_id_class", "unit_id_unit"),
                name="user_id_class_id_unit_id_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.CheckConstraint(
                check=models.Q(("class_size__gte", 0)), name="class_size_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("user_role__in", ["student", "lecturer", "admin"])),
                name="user_role_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user_status__in", ["active", "suspended", "unregistered"])
                ),
                name="user_status_ck",
            ),
        ),
    ]
