# Generated by Django 4.2.27 on 2026-02-24 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackitem",
            name="feedback_id_feedback",
            field=models.ForeignKey(
                db_column="feedback_id_feedback",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_items",
                to="core.feedback",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["unit_id_unit"], name="class_unit_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["user_id_user"], name="enrollment_user_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["class_id_class"], name="enrollment_class_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["unit_id_unit"], name="enrollment_unit_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["user_id_user"], name="feedback_user_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["submission_id_submission"], name="feedback_submission_idx"),
        ),
        migrations.AddIndex(
            model_name="feedbackitem",
            index=models.Index(fields=["feedback_id_feedback"], name="feedback_item_feedback_idx"),
        ),
        migrations.AddIndex(
            model_name="feedbackitem",
            index=models.Index(fields=["rubric_item_id_rubric_item"], name="feedback_item_rubric_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["user_id_user", "-submission_time"], name="submission_user_time_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["task_id_task"], name="submission_task_idx"),
        ),
    ]
