# Generated by Django 4.2.27 on 2026-02-25 03:51

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_dashboard_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enrollment_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enrollment_class_idx",
        ),
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enrollment_unit_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedback",
            name="feedback_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedback",
            name="feedback_submission_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedbackitem",
            name="feedback_item_feedback_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedbackitem",
            name="feedback_item_rubric_idx",
        ),
        migrations.RemoveIndex(
            model_name="submission",
            name="submission_user_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="submission",
            name="submission_task_idx",
        ),
        migrations.AddField(
            model_name="class",
            name="class_archived_at",
            field=models.DateTimeField(blank=True, db_comment="Archive timestamp", null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="class_desc",
            field=models.TextField(blank=True, db_comment="Class description", null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="class_join_code",
            field=models.CharField(db_comment="Student self-enrollment code", default="", max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="class",
            name="class_name",
            field=models.CharField(db_comment="Class name (e.g., CS101 Class A)", default="", max_length=100),
        ),
        migrations.AddField(
            model_name="class",
            name="class_status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                db_comment="Class status",
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_term",
            field=models.CharField(
                choices=[
                    ("semester1", "Semester 1"),
                    ("semester2", "Semester 2"),
                    ("term1", "Term 1"),
                    ("term2", "Term 2"),
                    ("full_year", "Full Year"),
                ],
                db_comment="Academic term",
                default="full_year",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_year",
            field=models.PositiveSmallIntegerField(db_comment="Academic year", default=core.models.get_current_year),
        ),
        migrations.AlterField(
            model_name="feedbackitem",
            name="feedback_id_feedback",
            field=models.ForeignKey(
                db_column="feedback_id_feedback", on_delete=django.db.models.deletion.CASCADE, to="core.feedback"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["class_join_code"], name="class_join_code_idx"),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.CheckConstraint(
                check=models.Q(("class_status__in", ["active", "archived"])), name="class_status_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.CheckConstraint(
                check=models.Q(("class_year__gte", 2000), ("class_year__lte", 2100)), name="class_year_range_ck"
            ),
        ),
    ]
