# Generated by Django 4.2.27 on 2026-02-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_enrollment_enrollment_user_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="submission",
            table_comment="A weak entity for task submissions.",
        ),
        migrations.AddField(
            model_name="task",
            name="task_allow_late_submission",
            field=models.BooleanField(db_comment="Allow late submissions", default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="task_desc",
            field=models.TextField(blank=True, db_comment="Short description", null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("unpublished", "Unpublished"),
                    ("archived", "Archived"),
                ],
                db_comment="Task status",
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(("task_status__in", ["draft", "published", "unpublished", "archived"])),
                name="task_status_ck",
            ),
        ),
    ]
