# Generated by Django 4.2.27 on 2026-02-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_task_missing_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_instructions",
            field=models.TextField(db_comment="Submission instructions"),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_title",
            field=models.CharField(db_comment="Task title", max_length=200),
        ),
    ]
