# Generated by Django 4.2.27 on 2026-02-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_fix_task_model_duplicates"),
    ]

    operations = [
        migrations.AddField(
            model_name="markingrubric",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                db_comment="Whether this rubric is visible to all users (public) or only the creator (private)",
                default="private",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="markingrubric",
            index=models.Index(fields=["visibility"], name="marking_rubric_visibility_idx"),
        ),
    ]
