# Generated by Django 4.2.27 on 2026-02-26 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_markingrubric_visibility_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "badge_id",
                    models.AutoField(db_comment="Unique identifier for badge", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_comment="Badge name", max_length=100)),
                ("description", models.CharField(db_comment="Badge description", max_length=200)),
                ("icon", models.CharField(db_comment="Icon name for display", max_length=50)),
                ("criteria", models.JSONField(db_comment="Criteria to earn this badge", default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_comment="Badge creation time")),
            ],
            options={
                "verbose_name": "badge",
                "verbose_name_plural": "badges",
                "db_table": "badge",
                "db_table_comment": "Achievement badges for users",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.JSONField(
                blank=True,
                db_comment="User preferences: email_notifications, in_app_notifications, submission_alerts, grading_alerts, weekly_digest, language, theme",
                default=dict,
            ),
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "user_badge_id",
                    models.AutoField(db_comment="Unique identifier for user badge", primary_key=True, serialize=False),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True, db_comment="Time when badge was earned")),
                (
                    "badge_id_badge",
                    models.ForeignKey(
                        db_column="badge_id_badge", on_delete=django.db.models.deletion.CASCADE, to="core.badge"
                    ),
                ),
                (
                    "user_id_user",
                    models.ForeignKey(
                        db_column="user_id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_badge",
                "db_table_comment": "User earned badges",
                "managed": True,
                "indexes": [models.Index(fields=["user_id_user"], name="user_badge_user_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(fields=("user_id_user", "badge_id_badge"), name="user_badge_unique"),
        ),
    ]
