# Generated by Django 4.2.23 on 2025-12-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_default_groups"),
        ("core", "0008_alter_user_table_comment"),
    ]

    operations = []
