# Generated by Django 4.2.23 on 2025-12-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_merge_20251213_0440"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={
                "managed": True,
                "verbose_name": "class",
                "verbose_name_plural": "classes",
            },
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="feedbackitem",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="markingrubric",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="rubricitem",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="rubricleveldesc",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="teachingassn",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"managed": True},
        ),
    ]
