# Generated by Django 4.2.27 on 2026-02-28 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_badge_user_preferences_userbadge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadlineExtension",
            fields=[
                (
                    "extension_id",
                    models.AutoField(
                        db_comment="Unique identifier for deadline extension", primary_key=True, serialize=False
                    ),
                ),
                ("original_deadline", models.DateTimeField(db_comment="Original task deadline at time of extension")),
                ("extended_deadline", models.DateTimeField(db_comment="New extended deadline for this student")),
                ("reason", models.TextField(blank=True, db_comment="Reason for extension", default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_comment="When extension was granted")),
                (
                    "granted_by",
                    models.ForeignKey(
                        db_column="granted_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task_id_task",
                    models.ForeignKey(
                        db_column="task_id_task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadline_extensions",
                        to="core.task",
                    ),
                ),
                (
                    "user_id_user",
                    models.ForeignKey(
                        db_column="user_id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadline_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deadline_extension",
                "db_table_comment": "Per-student deadline extensions for tasks",
                "managed": True,
                "indexes": [
                    models.Index(fields=["task_id_task"], name="extension_task_idx"),
                    models.Index(fields=["user_id_user"], name="extension_user_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="deadlineextension",
            constraint=models.UniqueConstraint(fields=("task_id_task", "user_id_user"), name="task_user_extension_uq"),
        ),
        migrations.AddConstraint(
            model_name="deadlineextension",
            constraint=models.CheckConstraint(
                check=models.Q(("extended_deadline__gt", models.F("original_deadline"))),
                name="extension_after_original_ck",
            ),
        ),
    ]
