# Generated by Django 4.2.30 on 2026-09-24 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_deadlineextension_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLeadAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_course_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit_id_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_lead_assignments",
                        to="core.unit",
                    ),
                ),
                (
                    "user_id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_lead_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "course_lead_assignment",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(choices=[("student", "Student"), ("lecturer", "Lecturer")], max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "class_id_class",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.class"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead_unit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.unit"
                    ),
                ),
            ],
            options={
                "db_table": "invitation",
                "indexes": [models.Index(fields=["email", "role"], name="invitation_email_role_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="courseleadassignment",
            constraint=models.UniqueConstraint(
                fields=("user_id_user", "unit_id_unit"), name="course_lead_user_unit_uq"
            ),
        ),
    ]
