# Generated by Django 4.2.30 on 2026-09-24 23:25

from django.db import migrations, models


def activate_legacy_null_status(apps, schema_editor):
    user_model = apps.get_model("core", "User")
    user_model.objects.filter(user_status__isnull=True).update(user_status="active")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_courseleadassignment_invitation_and_more"),
    ]

    operations = [
        migrations.RunPython(activate_legacy_null_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="user_status",
            field=models.CharField(db_column="user_status", default="active", max_length=15),
        ),
    ]
