# Generated by Django 4.2.30 on 2026-09-24 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_user_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentAuditEvent",
            fields=[
                ("event_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "assessment_audit_event",
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="ai_proposal",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="rubric_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("ai_pending", "AI pending"),
                    ("ai_draft", "AI draft"),
                    ("lecturer_reviewed", "Lecturer reviewed"),
                    ("published", "Published"),
                ],
                default="ai_pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["ai_pending", "ai_draft", "lecturer_reviewed", "published"])),
                name="feedback_status_ck",
            ),
        ),
        migrations.AddField(
            model_name="assessmentauditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="assessmentauditevent",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="core.feedback"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentauditevent",
            index=models.Index(fields=["feedback", "created_at"], name="assessment_audit_lookup_idx"),
        ),
    ]
