# Generated by Django 4.2.30 on 2026-09-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_assessmentauditevent_feedback_ai_proposal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubricitem",
            name="rubric_item_weight",
            field=models.DecimalField(
                db_comment="the weight of the item on a scale of 100%, using xx.x", decimal_places=1, max_digits=4
            ),
        ),
    ]
