# Generated by Django 4.2.30 on 2026-09-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_rubricitem_rubric_item_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="final_score",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
