# Generated by Django 4.2.30 on 2026-09-25 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_feedback_final_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="user_id_user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id_user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
