# Generated by Django 4.2.30 on 2026-09-25 00:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_feedback_user_id_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIJob",
            fields=[
                ("job_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("provider", models.CharField(default="codex", max_length=40)),
                ("model", models.CharField(default="gpt-6-luna", max_length=80)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("usage", models.JSONField(blank=True, null=True)),
                ("provider_thread_id", models.CharField(blank=True, default="", max_length=80)),
                ("error_category", models.CharField(blank=True, default="", max_length=40)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ai_job", to="core.submission"
                    ),
                ),
            ],
            options={
                "db_table": "ai_job",
                "indexes": [models.Index(fields=["status", "lease_expires_at"], name="ai_job_claim_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="aijob",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["pending", "running", "succeeded", "failed"])), name="ai_job_status_ck"
            ),
        ),
    ]
