# Generated by Django 4.2.30 on 2026-09-25 00:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_aijob_aijob_ai_job_status_ck"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeEssay",
            fields=[
                ("essay_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("goal", models.TextField()),
                ("content", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(choices=[("en", "English"), ("zh", "Chinese")], default="en", max_length=2),
                ),
                ("audience", models.CharField(blank=True, max_length=80)),
                ("tone", models.CharField(blank=True, max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rubric",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.markingrubric"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_essays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "practice_essay",
            },
        ),
        migrations.CreateModel(
            name="PracticeRevision",
            fields=[
                (
                    "revision_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("number", models.PositiveIntegerField()),
                ("goal", models.TextField()),
                ("content", models.TextField()),
                ("language", models.CharField(max_length=2)),
                ("audience", models.CharField(blank=True, max_length=80)),
                ("tone", models.CharField(blank=True, max_length=80)),
                ("rubric_snapshot", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="core.practiceessay"
                    ),
                ),
            ],
            options={
                "db_table": "practice_revision",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="PracticeRun",
            fields=[
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(default="pending", max_length=12)),
                ("provider", models.CharField(default="codex", max_length=40)),
                ("model", models.CharField(default="gpt-6-luna", max_length=80)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("report", models.JSONField(blank=True, null=True)),
                ("usage", models.JSONField(blank=True, null=True)),
                ("provider_thread_id", models.CharField(blank=True, default="", max_length=80)),
                ("error_category", models.CharField(blank=True, default="", max_length=40)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="run", to="core.practicerevision"
                    ),
                ),
            ],
            options={
                "db_table": "practice_run",
            },
        ),
        migrations.CreateModel(
            name="PracticeEvidence",
            fields=[
                ("evidence_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("claim", models.TextField()),
                ("query", models.CharField(max_length=200)),
                ("verdict", models.CharField(default="unresolved", max_length=15)),
                ("rationale", models.TextField(blank=True)),
                ("source_title", models.CharField(blank=True, max_length=300)),
                ("source_url", models.URLField(blank=True, max_length=600)),
                ("source_excerpt", models.TextField(blank=True)),
                ("supporting_quote", models.TextField(blank=True)),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="evidence", to="core.practicerun"
                    ),
                ),
            ],
            options={
                "db_table": "practice_evidence",
            },
        ),
        migrations.AddIndex(
            model_name="practicerun",
            index=models.Index(fields=["status", "lease_expires_at"], name="practice_run_claim_idx"),
        ),
        migrations.AddConstraint(
            model_name="practicerun",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["pending", "running", "succeeded", "failed"])),
                name="practice_run_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="practicerevision",
            constraint=models.UniqueConstraint(fields=("essay", "number"), name="practice_revision_number_uq"),
        ),
        migrations.AddConstraint(
            model_name="practiceevidence",
            constraint=models.CheckConstraint(
                check=models.Q(("verdict__in", ["supported", "contradicted", "unresolved"])),
                name="practice_evidence_verdict_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="practiceessay",
            index=models.Index(fields=["student", "updated_at"], name="practice_essay_owner_idx"),
        ),
        migrations.AddConstraint(
            model_name="practiceessay",
            constraint=models.CheckConstraint(
                check=models.Q(("language__in", ["en", "zh"])), name="practice_essay_lang_ck"
            ),
        ),
    ]
