# Generated by Django 4.2.30 on 2026-09-25 00:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_practiceessay_practicerevision_practicerun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeChatTurn",
            fields=[
                ("turn_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=12)),
                ("model", models.CharField(default="gpt-6-luna", max_length=80)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("usage", models.JSONField(blank=True, null=True)),
                ("provider_thread_id", models.CharField(blank=True, default="", max_length=80)),
                ("error_category", models.CharField(blank=True, default="", max_length=40)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="chat_turns", to="core.practicerun"
                    ),
                ),
            ],
            options={
                "db_table": "practice_chat_turn",
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["status", "lease_expires_at"], name="practice_chat_claim_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="practicechatturn",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["pending", "running", "succeeded", "failed"])),
                name="practice_chat_status_ck",
            ),
        ),
    ]
