# Generated by Django 4.2.30 on 2026-09-25 01:44

from django.db import migrations, models


def freeze_existing_tasks(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    MarkingRubric = apps.get_model("core", "MarkingRubric")
    RubricItem = apps.get_model("core", "RubricItem")
    RubricLevelDesc = apps.get_model("core", "RubricLevelDesc")
    database = schema_editor.connection.alias
    for task in Task.objects.using(database).exclude(task_status="draft").iterator():
        rubric = MarkingRubric.objects.using(database).filter(pk=task.rubric_id_marking_rubric_id).first()
        if rubric is None:
            continue
        items = []
        for item in RubricItem.objects.using(database).filter(rubric_id_marking_rubric_id=rubric.pk):
            levels = list(RubricLevelDesc.objects.using(database).filter(rubric_item_id_rubric_item_id=item.pk))
            if not levels:
                items = []
                break
            items.append({
                "id": item.pk,
                "name": item.rubric_item_name,
                "weight": str(item.rubric_item_weight),
                "max_score": max(level.level_max_score for level in levels),
                "levels": [
                    {"min": level.level_min_score, "max": level.level_max_score, "description": level.level_desc}
                    for level in levels
                ],
            })
        if items:
            task.rubric_snapshot = {
                "rubric_id": rubric.pk,
                "description": rubric.rubric_desc or "",
                "items": items,
            }
            task.rubric_version = 1
            task.save(update_fields=["rubric_snapshot", "rubric_version"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_practicechatturn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="rubric_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="rubric_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(freeze_existing_tasks, migrations.RunPython.noop),
    ]
