# Generated by Django 4.2.30 on 2026-09-25 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_supportticket_supportticket_ticket_status_ck_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AdminAuditEvent",
            fields=[
                ("event_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=40)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_audit_event",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["target", "created_at"], name="admin_audit_target_idx")],
            },
        ),
    ]
