# Generated by Django 4.2.30 on 2026-09-25 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_passwordresetgrant"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedEssay",
            fields=[
                ("share_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("class", "Class"), ("anonymous", "Anonymous")], max_length=12
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("visible", "Visible"), ("hidden", "Hidden"), ("removed", "Removed")],
                        default="visible",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="shared_essays", to="core.class"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_essays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="social_share", to="core.submission"
                    ),
                ),
            ],
            options={
                "db_table": "shared_essay",
            },
        ),
        migrations.CreateModel(
            name="SocialInteraction",
            fields=[
                ("interaction_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("bookmark", "Bookmark"),
                            ("comment", "Comment"),
                            ("feedback", "Feedback"),
                        ],
                        max_length=12,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="interactions", to="core.sharedessay"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "social_interaction",
            },
        ),
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                ("report_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("offensive", "Offensive"),
                            ("inappropriate", "Inappropriate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("decision", models.CharField(blank=True, max_length=20)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.socialinteraction"
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="social_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_social_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="reports", to="core.sharedessay"
                    ),
                ),
            ],
            options={
                "db_table": "social_content_report",
            },
        ),
        migrations.CreateModel(
            name="SocialPostingBan",
            fields=[
                ("ban_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("expires_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posting_bans", to="core.class"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_posting_bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posting_bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "social_posting_ban",
                "indexes": [models.Index(fields=["user", "class_obj", "expires_at"], name="social_ban_lookup_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="socialinteraction",
            constraint=models.CheckConstraint(
                check=models.Q(("interaction_type__in", ["like", "bookmark", "comment", "feedback"])),
                name="social_interaction_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="socialinteraction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("interaction_type__in", ["like", "bookmark"])),
                fields=("share", "user", "interaction_type"),
                name="social_toggle_unique_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="sharedessay",
            index=models.Index(fields=["status", "created_at"], name="shared_essay_feed_idx"),
        ),
        migrations.AddConstraint(
            model_name="sharedessay",
            constraint=models.CheckConstraint(
                check=models.Q(("visibility__in", ["public", "class", "anonymous"])), name="shared_essay_visibility_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="sharedessay",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["visible", "hidden", "removed"])), name="shared_essay_status_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.CheckConstraint(
                check=models.Q(("reason__in", ["spam", "offensive", "inappropriate", "other"])),
                name="social_report_reason_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["open", "investigating", "resolved", "dismissed"])),
                name="social_report_status_ck",
            ),
        ),
    ]
