# Generated by Django 4.2.30 on 2026-09-25 02:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_sharedessay_socialinteraction_contentreport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                ("setting_id", models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ("name", models.CharField(default="EssayCoach", max_length=120)),
                ("logo_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#0f766e", max_length=7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "organization_settings",
            },
        ),
        migrations.CreateModel(
            name="AuthSession",
            fields=[
                ("session_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("refresh_jti", models.CharField(blank=True, max_length=100)),
                ("device", models.CharField(default="Unknown device", max_length=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_session",
            },
        ),
        migrations.AddConstraint(
            model_name="organizationsettings",
            constraint=models.CheckConstraint(check=models.Q(("setting_id", 1)), name="single_organization_ck"),
        ),
        migrations.AddIndex(
            model_name="authsession",
            index=models.Index(fields=["user", "expires_at"], name="auth_session_user_idx"),
        ),
    ]
