# Generated by Django 4.2.30 on 2026-09-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_organizationsettings_authsession_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                ("worker_id", models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ("last_seen_at", models.DateTimeField()),
                ("processed_jobs", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "worker_heartbeat",
            },
        ),
        migrations.AddConstraint(
            model_name="workerheartbeat",
            constraint=models.CheckConstraint(check=models.Q(("worker_id", 1)), name="single_ai_worker_heartbeat_ck"),
        ),
    ]
