# Generated by Django 4.2.30 on 2026-09-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_workerheartbeat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.CharField(blank=True, default="", max_length=240),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_show_essays",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_show_scores",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("classmates", "Classmates"), ("institution", "Institution")],
                default="classmates",
                max_length=12,
            ),
        ),
    ]
