# Generated by Django 4.2.30 on 2026-09-25 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_user_avatar_url_user_bio_user_profile_show_essays_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("notification_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_key", models.CharField(max_length=140, unique=True)),
                ("kind", models.CharField(max_length=30)),
                ("title_en", models.CharField(max_length=140)),
                ("title_zh", models.CharField(max_length=140)),
                ("body_en", models.CharField(max_length=300)),
                ("body_zh", models.CharField(max_length=300)),
                ("link", models.CharField(max_length=240)),
                ("in_app_visible", models.BooleanField(default=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "created_at"], name="notification_owner_idx")],
            },
        ),
    ]
