# Generated by Django 4.2.30 on 2026-09-25 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailChangeGrant",
            fields=[
                ("grant_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("old_email", models.EmailField(max_length=254)),
                ("new_email", models.EmailField(max_length=254)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_change_grant",
                "indexes": [models.Index(fields=["user", "expires_at"], name="email_change_owner_idx")],
            },
        ),
    ]
