# Generated by Django 4.2.30 on 2026-09-25 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_emailchangegrant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassLeaveRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("declined", "Declined")],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="leave_requests", to="core.class"
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "class_leave_request",
            },
        ),
        migrations.AddConstraint(
            model_name="classleaverequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("student", "class_obj"),
                name="one_pending_class_leave_request",
            ),
        ),
    ]
