# Generated by Django 4.2.30 on 2026-09-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_classleaverequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_allow_resubmission",
            field=models.BooleanField(db_comment="Allow one immutable revised submission", default=False),
        ),
    ]
