# Generated by Django 4.2.30 on 2026-09-25 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_task_task_allow_resubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpArticleVote",
            fields=[
                ("vote_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("article_slug", models.CharField(max_length=100)),
                ("helpful", models.BooleanField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_article_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "help_article_vote",
            },
        ),
        migrations.AddConstraint(
            model_name="helparticlevote",
            constraint=models.UniqueConstraint(fields=("user", "article_slug"), name="help_article_user_vote_uq"),
        ),
    ]
