# Generated by Django 4.2.30 on 2026-09-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_helparticlevote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rubricitem",
            name="exemplar_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
