# Generated by Django 4.2.30 on 2026-10-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_rubricitem_exemplar_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                ("event_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "login_event"},
        ),
        migrations.AddIndex(
            model_name="loginevent",
            index=models.Index(fields=["created_at"], name="login_event_created_idx"),
        ),
    ]
