# Generated by Django 4.2.30 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_loginevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginRateLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_hash", models.CharField(max_length=64, unique=True)),
                ("failure_count", models.PositiveSmallIntegerField(default=0)),
                ("window_started_at", models.DateTimeField()),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "login_rate_limit"},
        ),
    ]
