# Generated by Django 4.2.30 on 2026-10-01 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_loginratelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditevent',
            name='target_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='adminauditevent',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
