# Generated by Django 4.2.30 on 2026-10-02 01:27

from django.db import migrations, models
from django.db.models import Q


def backfill_report_targets(apps, schema_editor):
    """Record what each existing report targets and snapshot reported responses.

    Reports that still link a response become response reports. A report with no
    linked response is an essay report, except where the old resolver left its
    mark: a "remove" decision on a response deleted that response and cleared
    the link, but left the essay unremoved (an essay "remove" set the essay to
    removed, which could never be restored). Those become response reports whose
    response is gone; whether it was a comment or feedback is no longer known,
    so they are recorded as comments with an empty snapshot.
    """
    ContentReport = apps.get_model("core", "ContentReport")
    reports = ContentReport.objects.filter(interaction__isnull=False).select_related("interaction__user")
    for report in reports.iterator():
        interaction = report.interaction
        user = interaction.user
        author = f"{user.user_fname or ''} {user.user_lname or ''}".strip() or user.user_email
        # Only comments and feedback can be reported; any legacy report on another
        # interaction kind is still a response report, so record it as a comment.
        report.target_type = interaction.interaction_type if interaction.interaction_type == "feedback" else "comment"
        report.target_content = interaction.content
        report.target_author = author
        report.save(update_fields=["target_type", "target_content", "target_author"])
    detached = ContentReport.objects.filter(interaction__isnull=True)
    removed_response = Q(decision="remove") & ~Q(share__status="removed")
    detached.filter(removed_response).update(target_type="comment")
    detached.exclude(removed_response).update(target_type="essay")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_preserve_account_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentreport",
            name="target_author",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="target_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="target_type",
            field=models.CharField(
                choices=[("essay", "Essay"), ("comment", "Comment"), ("feedback", "Feedback")],
                default="essay",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="socialinteraction",
            name="status",
            field=models.CharField(
                choices=[("visible", "Visible"), ("hidden", "Hidden"), ("removed", "Removed")],
                default="visible",
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.CheckConstraint(
                check=models.Q(("target_type__in", ["essay", "comment", "feedback"])),
                name="social_report_target_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="socialinteraction",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["visible", "hidden", "removed"])), name="social_interaction_status_ck"
            ),
        ),
        migrations.RunPython(backfill_report_targets, migrations.RunPython.noop),
    ]
